version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
