version: '3.8'

services:
  app:
    image: taiquan03a/springboot-app:test
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: booking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#
#  redis:
#    image: redis:latest
#    container_name: redis-cache
#    restart: always
#    ports:
#      - "6379:6379"

volumes:
  mysql_data:
