package com.ptit.booking.configuration;

import com.google.api.client.util.Value;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.messaging.FirebaseMessaging;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Base64;

@Configuration
public class FirebaseConfig {

    private String fireBaseConfigFilePath = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYm9va2luZ2FwcC00MTI1NiIsCiAgInByaXZhdGVfa2V5X2lkIjogImE1ODY3ZGYwZWY5YmZmMmZlNGUwOGRhNTI4MzcyYWQzOWRkZTc1ZjQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREFVMUVIb1dsL3czK1VcbmtlZm9PMlM5UGZaUE90Z3cxY2hOUkV6OXBaMFlhODZJdkMvME1vQ0Nrd1lta3RCbUw2eVJLckdqWm5XUGRmNlZcbmZwUFlINXl0eXBQODZocmRKbWdheTFQbk84VXlXTmljVkpHZXExUnBhMVRaT0ZnREpsT281eWUwZFQ5NG1qN1ZcbnEwRmc5RlFGbDlrMjdBdHpKbkVpcW15QTJ5N3I3Si9hQUNkMUlwbDdVWVpZMktUS2JPOFZuT2xUZnBQNFpxaDFcbm5VWjBnd0dIelZOWHNuTkpuTDc4M3pUUWtxUTJMRVA3VUVOZGk1V0MwQm9xUHdCRlorK2poMVJSMjJmZUJWOUtcbjEvLzFVemJMRU1wTXUrOSs3QTZMa0wvRU1ZZmpvcnVBeUhGbEhsdUxra1lBNnkzYXQ1ckVHMWpJVDRzOVpTbDFcbmRwalJ6SXl2QWdNQkFBRUNnZ0VBR2VZK1o3b25aR0sxMkJLTCtkeWh0TkJXenBXY2puc0RsZEFvVkJJTTVVQ0RcbldDdUxnNldYWTc0YjJtN3o3SWJvQk1hTWxIWVVSOFQ2aXpRNEFhZEVLSzA2bjVrQkZCMzdiL3hJcUwrR1QwRGlcbnJxNit5M0RFRmN3ejZXcXFnNFlTUnhFVjZqbk4yZFpmdHROd292ZFVKMHFySURmS1ZPL3MxVi9BNjl0WVpzSERcbmVBNmQ2L2ZWYWxjTFJVWWR2MkVETzYzbi9oNmZKd0kvMmdiRjByOUVQY0pPcHRVQ0dlRVlnYkNxNXhJQmpoV1RcblhpVCtQOTVNWFBnaUd5aDhuWDJZTFFxcjJuZ2p3US9MS3dWbGlicWY4T05ma1pQUlhjUmtRWitUS2tmZWNtOTlcblBEL1p1QkRNUnVLRG5FL2x5WHlhaStBMG9RdUdqR2hBdXo2NjlJSGptUUtCZ1FEbXlwdzU2eVUvc3hPb1Y5UERcbkU3RUtSRTNOcUV6c2JTT2hvbzhxTmowVXA1SmRlWVZibFR3c3dCbVVxVGV0ckhieUIyaWVvcWpoKzVHczJzaFFcbmd1aTYvRlJWbFNpQ2lQNTd2d244ZWFjZzFkdFlhV3JFQ2dXYk9wdEZpcUtDY25lMEVuUjhtckpiVXFOcmVYc3JcbjFNVE9vQkl2NEhqZm8vY1JEekFVcWdzOFJ3S0JnUURWVlI3T0gwUWFFRWdINk4vSUE0MFMwU0dFMFYwWlRocU5cbk9EM3V0MmMyQkJUVllFdlhnRTNoTDQzbWx3ak1LQUpvUUt6dnlnNEVMSkdMUUdSUk9pRXMxUEtMZlNGbnpKUElcbmNkQU9qMkN0Y2g0ZjVzbGo2b0JDTlF0eEY0U2xDeCt5WjZzYnRMSDhCbzNlalRIMW1OOE9xeWdyQUZoSTVCWEFcbk83V0JVZnFvV1FLQmdRREQ3MmxZeHFpMS9ydUdwU0cwTVVpUmxkR1Q4dmx6azJpM3RnSGpiVzdIMVVndXNaZWxcblcvcGRaNjJRQjJXc3ZZbXlDdFlvTDZJL1VNdXBPNGpxeVdqNkxuVU92M1pIOURSUkxLdzJ1N1ZHN0NpdlU3Zi9cbnZSNXJYZ01xcy9zcDBqS01IMHJqNnBYWGNENHJaVlJMcnZSekUzUzlUczV2MTQxTzMxMExmaDNSeXdLQmdRQ29cbnNDd3h0UXQyeUpVTW5Cb0g0TGIyd0NPUEVMWmJRaVZBc2M1WEt2TVVCVm9yOTM5QklwVnlrTlhXRm12QWM0cWpcbndUQitVL21OVjJpbkFmM1JOUFB5clZnMDhIY3Z5dGE0MHpZL3JTUTNRbHVMd2tSUkc2YmJzM0lldFFnUU1hR1lcbnd0ek1oYStQcCtjYXFlOXRVcnBlc1B5TU5ET2JQNi9yVjh1SVBMakYwUUtCZ0N3bVZZeVhOSWRROHlsVzc0NDZcbnE1K3RHdlVYY2JtMUlBWGw2V1BJdWdFK3VjWTdFZk9mZHJpU1dLKzRISW0wcWJ2MUNxWk5yVmRqcWNaNFBiSW1cbm5sN1dtVlNyeW5yYzN3RHQ4dWk2aGJRdEZWeWN5bnI0dk9LOVNKNE5yMGtlZkJxRFc5dTY1RlNXRVJZSld0aXdcbkFjSFIzSzBWMTN2Qmwzbk14OTlYUjd3alxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQGJvb2tpbmdhcHAtNDEyNTYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA0OTYwMDUyODA3NTkzMjY1ODkxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MGJvb2tpbmdhcHAtNDEyNTYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0=";

    @Bean
    public FirebaseApp initializeFirebase() throws IOException {
        if (fireBaseConfigFilePath == null || fireBaseConfigFilePath.isEmpty()) {
            throw new IllegalArgumentException("Firebase configuration is missing!");
        }
        //FileInputStream serviceAccount = new FileInputStream("src/main/resources/serviceAccountKey.json");
        byte[] decodedBytes = Base64.getDecoder().decode(fireBaseConfigFilePath);
        ByteArrayInputStream serviceAccount = new ByteArrayInputStream(decodedBytes);

        FirebaseOptions options = new FirebaseOptions.Builder()
                .setCredentials(GoogleCredentials.fromStream(serviceAccount))
                .build();

        FirebaseApp firebaseApp;
        if (FirebaseApp.getApps().isEmpty()) {
            firebaseApp = FirebaseApp.initializeApp(options);
        } else {
            firebaseApp = FirebaseApp.getInstance();
        }

        return firebaseApp;
    }

    @Bean
    public FirebaseMessaging firebaseMessaging(FirebaseApp firebaseApp) {
        return FirebaseMessaging.getInstance(firebaseApp);
    }
}
